src/blog/urls.py
from django.urls import re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    re_path(r'^$', views.BlogView.as_view(), name='blog'),
    re_path(r'^ru/$', views.BlogRuView.as_view(), name='blog'),
    url(r"^(?P<category_slug>.[\w-]+[']*)/$", views.category, name='category'),
    url(r"^ru/(?P<category_slug>.[\w-]+[']*)/$", views.categoryru, name='categoryru'),
    re_path(r"^team-member/(?P<member_slug>.+)/$", views.team, name='team_member'),
    re_path(r"^ru/team-member/(?P<member_slug>.+)/$", views.teamru, name='team_member_ru'),
    url(r"^article/(?P<article_slug>.+)/$", views.article, name='article'),
    url(r"^ru/article/(?P<article_slug>.+)/$", views.articleru, name='articleru'),
]

src/core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.views import LogoutView
from projectx import views as core_views
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from . import views


admin.site.index_title = 'ProjectX administration'

urlpatterns = [
    path('boss/', admin.site.urls),
    url(r'^ru/account/$', views.login_redirect_ru, name='login_redirect_ru'),
    url(r'^account/$', views.login_redirect, name='login_redirect'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^chat/', include('django_private_chat.urls')),
    re_path(r'', include(('projectx.urls', 'projectx'), namespace='projectx')),
    re_path(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
    re_path(r'^recipe/', include(('recipe.urls', 'recipe'), namespace='recipe')),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^logout/ru/$', views.LogoutRuView.as_view(), name='logout_ru'),
    url(r'^login/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^ru/login/',
        views.LoginRuView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^ru/signup/$', core_views.signupru, name='signupru'),



    path('ru/password_change/', views.PasswordChangeRuView.as_view(), name='password_change_ru'),
    path('ru/password_change/done/', views.PasswordChangeRuDoneView.as_view(), name='password_change_done_ru'),

    path('ru/password_reset/', views.PasswordResetRuView.as_view(), name='password_reset_ru'),
    path('ru/password_reset/done/', views.PasswordResetDoneRuView.as_view(), name='password_reset_done_ru'),
    path('ru/reset/<uidb64>/<token>/', views.PasswordResetConfirmRuView.as_view(), name='password_reset_confirm_ru'),
    path('ru/reset/done/', views.PasswordResetCompleteRuView.as_view(), name='password_reset_complete_ru'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.utils.translation import gettext as _
from core.models import BaseModel
from django.contrib.auth.models import User


class ArticleCategory(BaseModel):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Category In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Category In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Category In English'),
    )

    slug = models.CharField(
        max_length=150,
        unique=True,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    image = models.ImageField(verbose_name=_('Image'), null=True)

    author = models.ForeignKey(User,
                               related_name=_('article_category'),
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True,
                               verbose_name=_('Author'),
                               )

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name


class Comment(BaseModel):
    author = models.ForeignKey(User,
                               related_name=_('author'),
                               on_delete=models.CASCADE,
                               verbose_name=_('Author'),
                               )

    article = models.ForeignKey(to='Article',
                                related_name=_('article'),
                                on_delete=models.SET_NULL,
                                null=True,
                                verbose_name=_('Article'),
                                )

    comment = models.CharField(
        max_length=300,
        verbose_name=_('Comment'),
    )

    ban = models.BooleanField(default=False)

    def __str__(self):
        return self.author.username


class Article(BaseModel):
    name = models.CharField(
        max_length=150,
        verbose_name=_('Article Name In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Article Name In Russian'),
    )

    name_en = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Article Name In English'),
    )

    slug = models.CharField(
        max_length=150,
        unique=True,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    article_of_day = models.BooleanField(verbose_name=_('Article Of day'), default=False)

    author = models.ForeignKey(User,
                               related_name=_('article'),
                               on_delete=models.SET_NULL,
                               null=True,
                               verbose_name=_('Author'),
                               )

    category = models.ForeignKey(ArticleCategory,
                                 related_name=_('article'),
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 verbose_name=_('Category'),
                                 )

    description = models.CharField(
        max_length=1000,
        blank=True,
        verbose_name=_('Description'),
    )

    description_ru = models.CharField(
        max_length=1000,
        blank=True,
        verbose_name=_('Description Ru'),
    )

    description_en = models.CharField(
        max_length=1000,
        blank=True,
        verbose_name=_('Description En'),
    )

    first_half = models.TextField(max_length=5000, verbose_name=_('First Half'), blank=True, null=True)

    second_half = models.TextField(max_length=5000, verbose_name=_('Second Half'), blank=True, null=True)

    first_half_ru = models.TextField(max_length=5000, verbose_name=_('First Half Ru'), blank=True, null=True)

    second_half_ru = models.TextField(max_length=5000, verbose_name=_('Second Half Ru'), blank=True, null=True)

    first_half_en = models.TextField(max_length=5000, verbose_name=_('First Half En'), blank=True, null=True)

    second_half_en = models.TextField(max_length=5000, verbose_name=_('Second Half En'), blank=True, null=True)

    main_image = models.ImageField(verbose_name=_('Main Image'))

    image_1 = models.ImageField(verbose_name=_('Image 1'), blank=True, null=True)

    image_2 = models.ImageField(verbose_name=_('Image 2'), blank=True, null=True)

    image_3 = models.ImageField(verbose_name=_('Image 3'), blank=True, null=True)

    likes = models.ManyToManyField(User, blank=True, verbose_name=_('Likes'), related_name=_('likes'))

    def get_comments(self):
        a = Comment.objects.filter(article_id=self.id)
        return a.count()

    def __str__(self):
        return self.name

src/blog/forms.py
from django import forms
from blog import models
from transliterate.exceptions import LanguageDetectionError
import re
from transliterate import translit


def transliterate(text):
    pieces = str(re.sub('[\W]+', ' ', text)).lower().split(' ')
    result = []

    for piece in pieces:
        try:
            result.append(translit(piece, reversed=True))
        except LanguageDetectionError:
            result.append(piece)
    return '-'.join([r for r in result if r])


class ArticleForm(forms.ModelForm):
    def clean_slug(self):
        return transliterate(self.cleaned_data['name'])

    class Meta:
        model = models.Article
        fields = '__all__'


class ArticleCategoryForm(forms.ModelForm):
    def clean_slug(self):
        return transliterate(self.cleaned_data['name'])

    class Meta:
        model = models.ArticleCategory
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = '__all__'

src/blog/views.py
from core.views import BaseView
from .models import Article, ArticleCategory, Comment
from .forms import CommentForm
from projectx.models import Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt
from django.http import Http404, JsonResponse
from django.template.loader import render_to_string


class BlogView(BaseView):
    template_name = 'blog/blog.html'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.all().order_by('-id')
        popular = Article.objects.all().annotate(count=Count('likes')).order_by('-count')[:2]
        categories = ArticleCategory.objects.all()
        page = request.GET.get('page')
        paginator_article = Paginator(articles, 5)
        try:
            article = paginator_article.page(page)
        except PageNotAnInteger:
            article = paginator_article.page(1)
        except EmptyPage:
            article = paginator_article.page(paginator_article.num_pages)

        context.update({
            'articles': article,
            'popular': popular,
            'categories': categories,
        })
        return self.render_to_response(context)


def category(request, category_slug):
    category = ArticleCategory.objects.get(slug=category_slug)
    articles = Article.objects.filter(category_id=category.id).order_by('-id')
    popular = Article.objects.filter(category_id=category.id).annotate(count=Count('likes')).order_by('-count')[:2]
    categories = ArticleCategory.objects.all()
    page = request.GET.get('page')
    paginator_article = Paginator(articles, 5)
    try:
        article = paginator_article.page(page)
    except PageNotAnInteger:
        article = paginator_article.page(1)
    except EmptyPage:
        article = paginator_article.page(paginator_article.num_pages)
    return render(request, 'blog/blog-category.html', {'articles': article,
                                                       'popular': popular,
                                                       'categories': categories,
                                                       'category': category,
                                                       })


@csrf_exempt
def article(request, article_slug):
    article = Article.objects.get(slug=article_slug)
    author = article.author
    more = Article.objects.filter(author_id=author.id)[:3]
    comments = Comment.objects.filter(article_id=article.id).order_by('created')
    for i in comments:
        if i.ban:
            comments = comments.exclude(id=i.id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:article', article_slug=article.slug)
    else:
        form = CommentForm()
    user = request.user
    context = {'article': article,
               'more': more,
               'comments': comments,
               'form': form,
               'user': user,
               }
    if request.is_ajax():
        rendered = render_to_string('blog/article-2.html', context)
        response = {'html': rendered}
        return JsonResponse(response)
    else:
        return render(request, 'blog/article.html', context)


def team(request, member_slug):
    profile = Profile.objects.get(slug=member_slug)
    return render(request, 'blog/team_member.html', {'profile': profile, })


class BlogRuView(BaseView):
    template_name = 'blog/blog-ru.html'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.all().order_by('-id')
        popular = Article.objects.all().annotate(count=Count('likes')).order_by('-count')[:2]
        categories = ArticleCategory.objects.all()
        page = request.GET.get('page')
        paginator_article = Paginator(articles, 5)
        try:
            article = paginator_article.page(page)
        except PageNotAnInteger:
            article = paginator_article.page(1)
        except EmptyPage:
            article = paginator_article.page(paginator_article.num_pages)

        context.update({
            'articles': article,
            'popular': popular,
            'categories': categories,
        })
        return self.render_to_response(context)


def categoryru(request, category_slug):
    category = ArticleCategory.objects.get(slug=category_slug)
    articles = Article.objects.filter(category_id=category.id).order_by('-id')
    popular = Article.objects.filter(category_id=category.id).annotate(count=Count('likes')).order_by('-count')[:2]
    categories = ArticleCategory.objects.all()
    page = request.GET.get('page')
    paginator_article = Paginator(articles, 5)
    try:
        article = paginator_article.page(page)
    except PageNotAnInteger:
        article = paginator_article.page(1)
    except EmptyPage:
        article = paginator_article.page(paginator_article.num_pages)
    return render(request, 'blog/blog-category-ru.html', {'articles': article,
                                                       'popular': popular,
                                                       'categories': categories,
                                                       'category': category,
                                                       })


@csrf_exempt
def articleru(request, article_slug):
    article = Article.objects.get(slug=article_slug)
    author = article.author
    more = Article.objects.filter(author_id=author.id)[:3]
    comments = Comment.objects.filter(article_id=article.id).order_by('created')
    for i in comments:
        if i.ban:
            comments = comments.exclude(id=i.id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:articleru', article_slug=article.slug)
    else:
        form = CommentForm()
    user = request.user
    context = {'article': article,
               'more': more,
               'comments': comments,
               'form': form,
               'user': user,
               }
    if request.is_ajax():
        rendered = render_to_string('blog/article-2-ru.html', context)
        response = {'html': rendered}
        return JsonResponse(response)
    else:
        return render(request, 'blog/article-ru.html', context)


def teamru(request, member_slug):
    profile = Profile.objects.get(slug=member_slug)
    return render(request, 'blog/team_member-ru.html', {'profile': profile, })

src/blog/templates/blog/article-2-ru.html
{% load static %}
<div class="mt-6" id="comments">
          <a href="#" id="ajax-text-me" style="display: none">Натисни мене ніжно</a>
          <div class="js-scrollbar g-height-680 g-brd-around rounded g-pa-20 g-mb-30 shadow">
            {% for comment in comments %}
            <div class="media g-mb-30">
                {% if comment.author.profile.file %}
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-20" src="{{ comment.author.profile.file.url }}">
                {% else %}
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-20" src="{% static 'assets/img/icons/avatar.jpg' %}">
                {% endif %}
              <div class="media-body">
                <div class="d-flex align-items-start g-mb-15 g-mb-10--sm">
                  <div class="d-block">
                      {% if comment.author.profile.name %}
                        <h5 class="h6">{{ comment.author.profile.name }}</h5>
                      {% else %}
                        <h5 class="h6">{{ comment.author.username }}</h5>
                      {% endif %}
                    <span class="d-block g-color-gray-dark-v5 g-font-size-11">{{ comment.created|date:"d.m.y" }} {{ comment.created|time:"H:i" }}</span>
                  </div>
                </div>
                <p>{{ comment.comment }}</p>
              </div>
            </div>
            <hr class="g-brd-gray-light-v4">
            {% endfor %}
          </div>
            {% if user.is_authenticated %}
            <form method="post" id="add">
                {% csrf_token %}
                  <select name="author" style="display: none;" required="" id="id_author">
                      <option value="{{ user.id }}" style="display: none;" selected="">---------</option>
                  </select>
                <select name="article" style="display: none;" required="" id="id_article">
                    <option value="{{ article.id }}" style="display: none;" selected="">---------</option>
                </select>
                <div class="g-mb-30">
              <textarea name="comment" maxlength="300" required="" id="id_comment" class="form-control g-bg-secondary g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-py-13 g-px-15" rows="5" placeholder="Ваш комментарий..." ></textarea>
            </div>
              <div class="row mb-4 align-items-center">
                <div class="col-auto">
                  <input class="btn btn-success btn-block" type="submit" name="submit" value="Отправить">
                </div>
              </div>
            </form>
            {% else %}
            <div class="g-mb-30">
              <textarea class="form-control g-bg-secondary g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-py-13 g-px-15" rows="5" placeholder="Ваш комментарий..." disabled=""></textarea>
            </div>
            <div class="d-flex align-items-center">
                <a href="/login">
                    <input  class="btn btn-success g-font-size-12  mr-4" value="Войти">
                    </a>
              <p class="g-font-size-13 mb-0">Чтобы написать комментарий</p>
            </div>
            {% endif %}
        </div>
{% block js %}
<script src="{% static '/assets/lib/loaders.css/loaders.css.js' %}"></script>
<script src="{% static '/assets/lib/jquery.mb.ytplayer/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'assets1/vendor/jquery-migrate/jquery-migrate.min.js' %}"></script>

<script src="{% static 'assets1/vendor/malihu-scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'assets1/js/hs.core.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.tabs.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.scrollbar.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.go-to.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.counter.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.rating.js' %}"></script>


  <!-- JS Plugins Init. -->
  <script>
    $(document).on('ready', function () {
        // initialization of go to
        $.HSCore.components.HSGoTo.init('.js-go-to');

        // initialization of tabs
        $.HSCore.components.HSTabs.init('[role="tablist"]');

        // initialization of counters
        var counters = $.HSCore.components.HSCounter.init('[class*="js-counter"]');

        // initialization of rating
        $.HSCore.components.HSRating.init($('.js-rating'), {
          spacing: 2
        });

        // initialization of HSScrollBar component
        $.HSCore.components.HSScrollBar.init( $('.js-scrollbar') );
      });

      $(window).on('load', function () {
        // initialization of header
        $.HSCore.components.HSHeader.init($('#js-header'));
        $.HSCore.helpers.HSHamburgers.init('.hamburger');

        // initialization of HSMegaMenu component
        $('.js-mega-menu').HSMegaMenu({
          event: 'hover',
          pageContainer: $('.container'),
          breakpoint: 991
        });

        // initialization of horizontal progress bars
        setTimeout(function () { // important in this case
          var horizontalProgressBars = $.HSCore.components.HSProgressBar.init('.js-hr-progress-bar', {
            direction: 'horizontal',
            indicatorSelector: '.js-hr-progress-bar-indicator'
          });
        }, 1);
      });

      $(window).on('resize', function () {
        setTimeout(function () {
          $.HSCore.components.HSTabs.init('[role="tablist"]');
        }, 200);
      });
  </script>


<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script>
  $(document).ready(function() {
    $('#add').ajaxForm(function() {
      document.getElementById("ajax-text-me").click();
    });
  });
    </script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ajax-text-me").click(function() {
            $.ajax({
                type: 'GET',
                async: true,
                url: '/blog/article/{{ article.slug }}/',
                data: "article_slug={{ article.slug }}",
                success: function(data) {
                    $("#comments").replaceWith(data['html']);
                    $('html, body').animate({
                    scrollTop: $("#comments").offset().top
                    }, 0);
                },
                dataType: 'json',
            });
        });
    });
</script>

{% endblock %}

src/blog/templates/blog/article-2.html
{% load static %}
<div class="mt-6" id="comments">
          <a href="#" id="ajax-text-me" style="display: none">Натисни мене ніжно</a>
          <div class="js-scrollbar g-height-680 g-brd-around rounded g-pa-20 g-mb-30 shadow">
            {% for comment in comments %}
            <div class="media g-mb-30">
                {% if comment.author.profile.file %}
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-20" src="{{ comment.author.profile.file.url }}">
                {% else %}
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-20" src="{% static 'assets/img/icons/avatar.jpg' %}">
                {% endif %}
              <div class="media-body">
                <div class="d-flex align-items-start g-mb-15 g-mb-10--sm">
                  <div class="d-block">
                      {% if comment.author.profile.name %}
                        <h5 class="h6">{{ comment.author.profile.name }}</h5>
                      {% else %}
                        <h5 class="h6">{{ comment.author.username }}</h5>
                      {% endif %}
                    <span class="d-block g-color-gray-dark-v5 g-font-size-11">{{ comment.created|date:"d.m.y" }} {{ comment.created|time:"H:i" }}</span>
                  </div>
                </div>
                <p>{{ comment.comment }}</p>
              </div>
            </div>
            <hr class="g-brd-gray-light-v4">
            {% endfor %}
          </div>
            {% if user.is_authenticated %}
            <form method="post" id="add">
                {% csrf_token %}
                  <select name="author" style="display: none;" required="" id="id_author">
                      <option value="{{ user.id }}" style="display: none;" selected="">---------</option>
                  </select>
                <select name="article" style="display: none;" required="" id="id_article">
                    <option value="{{ article.id }}" style="display: none;" selected="">---------</option>
                </select>
                <div class="g-mb-30">
              <textarea name="comment" maxlength="300" required="" id="id_comment" class="form-control g-bg-secondary g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-py-13 g-px-15" rows="5" placeholder="Ваш коментар..." ></textarea>
            </div>
              <div class="row mb-4 align-items-center">
                <div class="col-auto">
                  <input class="btn btn-success btn-block" type="submit" name="submit" value="Відправити">
                </div>
              </div>
            </form>
            {% else %}
            <div class="g-mb-30">
              <textarea class="form-control g-bg-secondary g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-py-13 g-px-15" rows="5" placeholder="Ваш коментар..." disabled=""></textarea>
            </div>
            <div class="d-flex align-items-center">
                <a href="/login">
                    <input  class="btn btn-success g-font-size-12  mr-4" value="Увійти">
                    </a>
              <p class="g-font-size-13 mb-0">Увійдіть, щоб написати коментар</p>
            </div>
            {% endif %}
        </div>
{% block js %}
<script src="{% static '/assets/lib/loaders.css/loaders.css.js' %}"></script>
<script src="{% static '/assets/lib/jquery.mb.ytplayer/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'assets1/vendor/jquery-migrate/jquery-migrate.min.js' %}"></script>

<script src="{% static 'assets1/vendor/malihu-scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'assets1/js/hs.core.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.tabs.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.scrollbar.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.go-to.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.counter.js' %}"></script>
<script src="{% static 'assets1/js/components/hs.rating.js' %}"></script>


  <!-- JS Plugins Init. -->
  <script>
    $(document).on('ready', function () {
        // initialization of go to
        $.HSCore.components.HSGoTo.init('.js-go-to');

        // initialization of tabs
        $.HSCore.components.HSTabs.init('[role="tablist"]');

        // initialization of counters
        var counters = $.HSCore.components.HSCounter.init('[class*="js-counter"]');

        // initialization of rating
        $.HSCore.components.HSRating.init($('.js-rating'), {
          spacing: 2
        });

        // initialization of HSScrollBar component
        $.HSCore.components.HSScrollBar.init( $('.js-scrollbar') );
      });

      $(window).on('load', function () {
        // initialization of header
        $.HSCore.components.HSHeader.init($('#js-header'));
        $.HSCore.helpers.HSHamburgers.init('.hamburger');

        // initialization of HSMegaMenu component
        $('.js-mega-menu').HSMegaMenu({
          event: 'hover',
          pageContainer: $('.container'),
          breakpoint: 991
        });

        // initialization of horizontal progress bars
        setTimeout(function () { // important in this case
          var horizontalProgressBars = $.HSCore.components.HSProgressBar.init('.js-hr-progress-bar', {
            direction: 'horizontal',
            indicatorSelector: '.js-hr-progress-bar-indicator'
          });
        }, 1);
      });

      $(window).on('resize', function () {
        setTimeout(function () {
          $.HSCore.components.HSTabs.init('[role="tablist"]');
        }, 200);
      });
  </script>


<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script>
  $(document).ready(function() {
    $('#add').ajaxForm(function() {
      document.getElementById("ajax-text-me").click();
    });
  });
    </script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ajax-text-me").click(function() {
            $.ajax({
                type: 'GET',
                async: true,
                url: '/blog/article/{{ article.slug }}/',
                data: "article_slug={{ article.slug }}",
                success: function(data) {
                    $("#comments").replaceWith(data['html']);
                    $('html, body').animate({
                    scrollTop: $("#comments").offset().top
                    }, 0);
                },
                dataType: 'json',
            });
        });
    });
</script>

{% endblock %}