src/core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.views import LogoutView
from projectx import views as core_views
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from . import views


admin.site.index_title = 'ProjectX administration'

urlpatterns = [
    path('boss/', admin.site.urls),
    url(r'^ru/account/$', views.login_redirect_ru, name='login_redirect_ru'),
    url(r'^account/$', views.login_redirect, name='login_redirect'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^chat/', include('django_private_chat.urls')),
    re_path(r'', include(('projectx.urls', 'projectx'), namespace='projectx')),
    re_path(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
    re_path(r'^recipe/', include(('recipe.urls', 'recipe'), namespace='recipe')),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^logout/ru/$', views.LogoutRuView.as_view(), name='logout_ru'),
    url(r'^login/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^ru/login/',
        views.LoginRuView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^ru/signup/$', core_views.signupru, name='signupru'),



    path('ru/password_change/', views.PasswordChangeRuView.as_view(), name='password_change_ru'),
    path('ru/password_change/done/', views.PasswordChangeRuDoneView.as_view(), name='password_change_done_ru'),

    path('ru/password_reset/', views.PasswordResetRuView.as_view(), name='password_reset_ru'),
    path('ru/password_reset/done/', views.PasswordResetDoneRuView.as_view(), name='password_reset_done_ru'),
    path('ru/reset/<uidb64>/<token>/', views.PasswordResetConfirmRuView.as_view(), name='password_reset_confirm_ru'),
    path('ru/reset/done/', views.PasswordResetCompleteRuView.as_view(), name='password_reset_complete_ru'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/projectx/urls.py
from django.urls import re_path
from django.conf.urls import url
import django.views.defaults
from . import views

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^contact/$', views.ContactView.as_view(), name='contact'),
    re_path(r'^private/$', views.PrivateView.as_view(), name='private'),
    re_path(r'^conditions/$', views.ConditionsView.as_view(), name='conditions'),
    re_path(r'^ru/private/$', views.PrivateRuView.as_view(), name='privateru'),
    re_path(r'^ru/conditions/$', views.ConditionsRuView.as_view(), name='conditionsru'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/$", views.profile, name='profile'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/diet/$", views.profile_diet, name='profile_diet'),

    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/category/(?P<meals_slug>.[\w-]+[']*)/(?P<category_slug>.[\w-]+[']*)/$", views.simple_category_recipe, name='simple_category_recipe'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/(?P<meals_slug>.[\w-]+[']*)/(?P<category_slug>.[\w-]+[']*)/(?P<recipe_slug>.+)/$", views.simple_recipe, name='simple_recipe'),

    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/friends/$", views.profile_friends, name='profile_friends'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/friends/search/$", views.friend_search, name='friend_search'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/recipes/$", views.profile_recipe, name='profile_recipe'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/recipes/search/$", views.recipe_search, name='recipe_search'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/recipes/(?P<category_slug>.[\w-]+[']*)/$", views.category_recipe, name='category_recipe'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/quick-decision/$", views.quick_decision, name='quick_decision'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/quick-decision/(?P<var>.[\w-]+[']*)/$", views.quick_decision_done, name='quick_decision_done'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/settings/$", views.profile_setting, name='profile_setting'),
    url(r"^profile/(?P<profile_slug>.[\w-]+[']*)/user/(?P<user_slug>.[\w-]+[']*)/$", views.profile_user, name='profile_user'),
    url(r'^form/$', views.infoform, name='info form'),
    re_path(r'^about/$', views.AboutView.as_view(), name='about'),
    re_path(r'^help/$', views.HelpView.as_view(), name='help'),

    re_path(r'^ru/$', views.IndexRuView.as_view(), name='indexru'),
    re_path(r'^ru/contact/$', views.ContactRuView.as_view(), name='contactru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/$", views.profileru, name='profileru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/diet/$", views.profile_dietru, name='profile_dietru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/category/(?P<meals_slug>.[\w-]+[']*)/(?P<category_slug>.[\w-]+[']*)/$",views.simple_category_reciperu, name='simple_category_reciperu'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/(?P<meals_slug>.[\w-]+[']*)/(?P<category_slug>.[\w-]+[']*)/(?P<recipe_slug>.+)/$",views.simple_reciperu, name='simple_reciperu'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/friends/$", views.profile_friendsru, name='profile_friendsru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/friends/search/$", views.friend_searchru, name='friend_searchru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/recipes/$", views.profile_reciperu, name='profile_reciperu'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/recipes/search/$", views.recipe_searchru, name='recipe_searchru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/recipes/(?P<category_slug>.[\w-]+[']*)/$", views.category_reciperu, name='category_reciperu'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/quick-decision/$", views.quick_decisionru, name='quick_decisionru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/quick-decision/(?P<var>.[\w-]+[']*)/$", views.quick_decision_doneru, name='quick_decision_doneru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/settings/$", views.profile_settingru, name='profile_settingru'),
    url(r"^ru/profile/(?P<profile_slug>.[\w-]+[']*)/user/(?P<user_slug>.[\w-]+[']*)/$", views.profile_userru, name='profile_userru',),
    url(r'^ru/form/$', views.infoformru, name='info form ru'),
    re_path(r'^ru/about/$', views.AboutRuView.as_view(), name='aboutru'),
    re_path(r'^ru/help/$', views.HelpRuView.as_view(), name='helpru'),
    url(r'^404/$', django.views.defaults.page_not_found, ),
    url(r'^pay-callback/$', views.PayCallbackView.as_view(), name='pay_callback'),
    url(r'^test/$', views.photo_list, name='test'),
]

src/recipe/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r"^ru/(?P<recipe_slug>.+)/$", views.reciperu, name='reciperu'),
    url(r"^(?P<recipe_slug>.+)/$", views.recipe, name='recipe'),
]

src/projectx/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext as _
from projectx.generator import generate_diet
from core.models import BaseModel
import datetime
from simple_history.models import HistoricalRecords


class MealsPerDay(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Meals Per Day'),
    )

    value = models.IntegerField(verbose_name=_('Value'), null=True)

    def __str__(self):
        return self.name


class MealsPerDayName(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Meals Per Day Name In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=64,
        verbose_name=_('Meals Per Day Name In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Meals Per Day Name In English'),
    )

    values = models.ManyToManyField(MealsPerDay)

    value = models.IntegerField(verbose_name=_('Value'))

    slug = models.CharField(verbose_name='Slug', max_length=150, null=True, blank=True)

    def __str__(self):
        return self.name


class Sex(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Sex In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Sex In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Sex In English'),
    )

    def __str__(self):
        return self.name


class LifeStyle(models.Model):
    name = models.CharField(
        max_length=128,
        unique=True,
        verbose_name=_('Life In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=128,
        unique=True,
        verbose_name=_('Life Style In Russian'),
    )

    name_en = models.CharField(
        max_length=128,
        blank=True,
        verbose_name=_('Life Style In English'),
    )

    def __str__(self):
        return self.name


class BodyType(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Body Type In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Body Type In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Body Type In English'),
    )

    description_en = models.CharField(
        max_length=512,
        blank=True,
        verbose_name=_('Description In English')
    )

    description_ru = models.CharField(
        max_length=512,
        blank=True,
        verbose_name=_('Description In Russian'),
    )

    description = models.CharField(
        max_length=512,
        blank=True,
        verbose_name=_('Description In Ukraine'),
    )

    def __str__(self):
        return self.name


class Index(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Index In Ukraine'),
    )

    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Index In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Index In English'),
    )

    description = models.CharField(
        max_length=512,
        blank=True,
        verbose_name=_('Description In English')
    )

    description_ru = models.CharField(
        max_length=512,
        verbose_name=_('Description In Russian'),
        blank=True,
    )

    description_ua = models.CharField(
        max_length=512,
        verbose_name=_('Description In Ukraine'),
        blank=True,
    )

    def __str__(self):
        return self.name


class Diet(BaseModel):
    boo = models.FloatField(verbose_name=_('BOO'), null=True)
    adaptation = models.FloatField(verbose_name=_('Adaptation'), null=True, default=0, blank=True)
    day_calories_norm = models.FloatField(verbose_name=_('Day Calories Norm'), null=True)

    day_target_calories = models.FloatField(verbose_name=_('Day Calories Target'), null=True)

    proteins = models.FloatField(verbose_name=_('Proteins'), null=True)

    carbohydrates = models.FloatField(verbose_name=_('Carbohydrates'), null=True)

    fats = models.FloatField(verbose_name=_('Fats'), null=True)

    water = models.IntegerField(verbose_name=_('Water'), null=True, default='2000')

    meals_per_day = models.IntegerField(verbose_name=_('Meals per day'), null=True)

    def __str__(self):
        if self.profile:
            return self.profile.user.username


DEFAULT_STATUS_ID = 1


class Profile(BaseModel):
    from recipe.models import Recipe
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('User'))
    user_status = models.ForeignKey(
        to='UserStatus',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('User Status'),
        default=DEFAULT_STATUS_ID,
    )
    order_id = models.CharField(verbose_name=_('Order id'), max_length=255, null=True, blank=True)
    last_update = models.DateTimeField(verbose_name='Last Update', null=True, blank=True)
    change_time = models.BooleanField(verbose_name=_('Change Time'), default=False)
    team_member = models.BooleanField(default=False)
    team_image = models.ImageField(verbose_name='Team Photo', null=True, blank=True)
    referral_code = models.CharField(verbose_name=_('Referral Cope'), max_length=10, null=True, blank=True)
    referrals = models.ManyToManyField(User, related_name=_('referrals'), blank=True)
    phone = models.CharField(verbose_name=_('Phone'), max_length=100, null=True, blank=True)
    friends = models.ManyToManyField(User, related_name=_('profile_friends'), blank=True)
    friend_request = models.ManyToManyField(User, related_name=_('friend_request'), blank=True)
    file = models.ImageField(verbose_name='Photo', null=True, blank=True)
    info_form = models.BooleanField(default=False)
    status = models.CharField(verbose_name='Status', max_length=100, null=True, blank=True)
    name = models.CharField(verbose_name='Name', max_length=100, null=True, blank=True)
    first_name = models.CharField(verbose_name='First Name', max_length=100, null=True, blank=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=100, null=True, blank=True)
    name_slug = models.CharField(verbose_name='Name Slug', max_length=150, null=True, blank=True)
    description_en = models.TextField(
        max_length=2000,
        blank=True,
        null=True,
        verbose_name=_('Description In English')
    )

    description_ru = models.TextField(
        max_length=2000,
        verbose_name=_('Description In Russian'),
        blank=True,
        null=True,
    )

    description = models.TextField(
        max_length=2000,
        verbose_name=_('Description In Ukraine'),
        blank=True,
        null=True,
    )

    facebook = models.URLField(verbose_name=_('Facebook'), blank=True, null=True)
    instagram = models.URLField(verbose_name=_('Instagram'), blank=True, null=True)
    you_tube = models.URLField(verbose_name=_('You_Tube'), blank=True, null=True)

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )
    sex = models.ForeignKey(
        to='Sex',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('Sex'),
    )
    age = models.IntegerField(null=True, blank=True, verbose_name=_('Age'),)
    growth = models.IntegerField(null=True, blank=True, verbose_name=_('Height'),)
    start_weight = models.IntegerField(null=True, blank=True, verbose_name=_('Start Weight'),)
    weight = models.FloatField(null=True, blank=True, verbose_name=_('Weight'),)
    target = models.ForeignKey(
        to='Target',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('Target'),
    )
    life_style = models.ForeignKey(
        to='LifeStyle',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('Life Style'),
    )
    body_type = models.ForeignKey(
        to='BodyType',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('Body Type'),
    )
    body_index = models.ForeignKey(
        to='Index',
        on_delete=models.CASCADE,
        verbose_name=_('Index'),
        null=True,
        blank=True,
    )

    diet = models.OneToOneField(
        to='Diet',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    recipes = models.ManyToManyField(Recipe, blank=True)

    delete_recipes = models.ManyToManyField(Recipe,
                                            blank=True,
                                            verbose_name=_('Delete Recipes'),
                                            related_name=_('delete_recipes')
                                            )

    subscription = models.BooleanField(default=False, verbose_name=_('Subscription'),)

    bonus = models.CharField(verbose_name=_('Bonus'), null=True, blank=True, max_length=20)

    subscription_ends = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_('Subscription ends at')
    )

    short_description = models.TextField(max_length=300, verbose_name=_('Short Description In Ukraine'), blank=True, null=True)
    short_description_ru = models.TextField(max_length=300, verbose_name=_('Short Description In Russian'), blank=True, null=True)
    short_description_en = models.TextField(max_length=300, verbose_name=_('Short Description In English'), blank=True, null=True)

src/projectx/templates/projectx/about-ru.html
{% extends 'core/base_ru.html' %}
{% load static %}

{% block title %}{{ _(' First Step | О сервисе') }}{% endblock %}
{% block content %}
      <section class="py-0" id="page-about">

        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-6 px-0 order-lg-2">
              <div class="sticky-top h-lg-100vh py-9">
                <div class="bg-holder" style="background-image:url({% static '/assets/img/about.jpg' %});">
                </div>
              </div>
            </div>
            <div class="col-lg-6 bg-white py-6">
              <div class="row h-100 align-items-center justify-content-center">
                <div class="col-lg-10">
                  <div class="mb-5">
                    <div class="overflow-hidden">
                      <h1 class="text-underline fs-4 fs-md-5 mb-0" data-zanim-xs='{"delay":0.4}' data-zanim-trigger="scroll">О First Step</h1>
                    </div>
                  </div>
                  <p class="dropcap" data-zanim-xs='{"delay":0.5}' data-zanim-trigger="scroll">First Step - это сервис для создания персональной диеты для каждого.
                    Главная идея которого - подобрать индивидуальный рацион с минимальными затратами усилий и времени. Все это достигается с помощью инновационного метода, созданного на основе многолетнего опыта работы специалистов в области диетологии и фитнеса, который позволяет построить диету с учетом всех основных данных пользователя.
                    База рецептов, адаптированных профессионалами, позволяет быстро и со вкусом получать качественный результат.
                    Постоянное дополнение и совершенствование алгоритма, позволяет не терять свою актуальность с течением времени и результатами пользователя. Адаптация рациона, отталкиваясь от результатов и вкусов каждого.
                    Дополняет все это возможность обсуждать и делиться впечатление со своими друзьями, не покидая сервис. Более того, мы предоставляем возможность общаться с профессионалами, которые приложили руку к созданию этого продукта, напрямую.
                    Такие функции как "блог" и "быстрое решение" помогут вам пополнить свои знания и получить быстрый ответ на вопросы, которые могут в вас возникнуть.
                  </p>
                  <div class="row mt-5">
                    <div class="col-6">
                      <img class="rounded img-fluid" src="{% static '/assets/img/about2.jpg' %}" alt="" data-zanim-xs='{"delay":0.6,"animation":"zoom-in"}' data-zanim-trigger="scroll" />
                    </div>
                    <div class="col-6">
                      <img class="rounded img-fluid" src="{% static '/assets/img/about1.jpg' %}" alt="" data-zanim-xs='{"delay":0.7,"animation":"zoom-in"}' data-zanim-trigger="scroll" />
                    </div>
                  </div>
                  <blockquote class="blockquote text-center my-6 border p-5 px-xl-7 border-300 rounded" data-zanim-xs='{"delay":0.1}' data-zanim-trigger="scroll">
                    <p class="blockquote-content">First Step - это шаг в здоровое будущее.</p>
                  </blockquote>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

src/projectx/templates/projectx/recipe-search-2-ru.html
{% load static %}
<div class="col-lg-9" id="search">
            <a href="#" id="ajax-text-me" style="display: none">Натисни мене ніжно</a>
            <div class="container">
                <form class="g-width-60x--md mx-auto" method="post">
                    {% csrf_token %}
                    <div class="form-group g-mb-20">
                        <div class="input-group u-shadow-v21 rounded g-mb-15">
                            <input class="form-control form-control-md g-brd-white g-font-size-16 border-right-0 pr-0 g-py-15" type="text" required name="name" maxlength="100" id="id_name" placeholder="Поиск рецептов">
                            <div class="input-group-addon d-flex align-items-center g-bg-white g-brd-white g-color-gray-light-v1 g-pa-2">
                                <button class="btn u-btn-primary g-font-size-16 g-py-15 g-px-20" type="submit">
                                    <i class="icon-magnifier g-pos-rel g-top-1"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-header d-flex align-items-center justify-content-between g-bg-green border-0 g-mb-15 u-shadow-v2">
                <h3 class="h6 mb-0">
                    <a class="text-white">Поиск рецептов</a>
                </h3>
            </div>
            <div class="row">
                {% for recipe in recipes %}
                <div class="col-lg-4">
                    <div class="card shadow p-3 mb-5 bg-white rounded">
                        {% if recipe.image %}
                        <a href="/recipe/ru/{{ recipe.slug }}"><img class="card-img-top" src="{{ recipe.image.url }}" alt="Card image cap"></a>
                        {% else %}
                        <a href="/recipe/ru/{{ recipe.slug }}"><img class="card-img-top" src="{% static 'assets/img/coming-soon.png' %}" alt="Card image cap"></a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name_ru }}</h5>
			    <h6 class="card-title">{{ recipe.description_ru }}</h6>
                        </div>
                        <hr class="g-brd-gray-light-v4 g-my-0">
                        <ul class="row list-inline g-py-20 g-ma-0">
                            <li class="col g-brd-right g-brd-gray-light-v4">
                            <div style="text-align: center">
                                <a class="u-icon-v1 u-icon-size--xs g-color-gray-dark-v5 g-bg-transparent g-color-cyan--hover" data-remodal-target="{{ recipe.id }}" href="#!" title="Добавить рецепт в рацион"><i>
                                    <img style="width: 100%" src="{% static 'assets/img/icons/plus.png' %}"></i>
                                </a>
                            </div>
                            </li>
                            <li class="col">
                            <div style="text-align: center">
                                <a class="u-icon-v1 u-icon-size--xs g-color-gray-dark-v5 g-bg-transparent g-color-purple--hover" data-remodal-target="{{ recipe.name_ru }}" href="#!" title="Не показывать этот рецепт">
                                    <i><img  style="width: 100%" src="{% static 'assets/img/icons/false.png' %}"></i>
                                </a>
                            </div>
                            </li>
                        </ul>
                    </div>
                    <div class="remodal" data-remodal-id="{{ recipe.id }}">
                        <button class="remodal-close" id="{{ recipe.id }}AddClose" data-remodal-action="close"></button>
                        <h4>Добавить в дневной рацион: {{ recipe.name_ru }}</h4>
                        <br>
                        <h5>Количество порций:</h5>
                        <h6>(за один прием пищи рекомендуется {{ recommend }} калорий)</h6>
                        <h6>1 порция: {{ recipe.portion }} {{ recipe.portion_data.name_ru }}, {{recipe.calories}} калорий.</h6>
                        <br>
                        <form method="post" id="{{ recipe.id }}Add">
                            {% csrf_token %}
                            <label for="id_user" style="display: none;">User:</label>
                            <select name="user" required="" id="id_user" style="display: none;">
                                <option value="{{ profile.user_id }}" style="display: none;" selected="">---------</option>
                            </select>
                            <h5>Прием пищи:</h5>
                            <label for="id_meals_per_day" style="display: none;">Meals Per Day Name:</label>
                            <select name="meals_per_day" id="id_meals_per_day" style="width: 75%" class="g-color-black g-bg-green">
                                <option value="" selected="">---------</option>
                                {% for meal in meals %}
                                <option value="{{ meal.id }}">{{ meal.name_ru }}</option>
                                {% endfor %}
                            </select>
                            <label for="id_recipe" style="display: none;">Recipes:</label>
                            <select name="recipe" id="id_recipe" style="display: none;">
                                <option value="{{ recipe.id }}" selected="">---------</option>
                            </select>
                            <br><br><h5>Количество порций:</h5>
                            <label for="id_portion_number" style="display: none;">Portion Number:</label>
                            <select name="portion_number" required="" id="id_portion_number" style="width: 75%" class="g-color-black g-bg-green">
                                <option value="" selected="">---------</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                            <br><br><br>
                            <button class="btn btn-sm btn-success mr-3" type="submit">Добавить</button>
                            <button class="btn btn-sm btn-outline-danger" data-remodal-action="cancel">Отменить</button>
                        </form>
                    </div>
                    <div class="remodal" data-remodal-id="{{ recipe.name_ru }}">
                        <button class="remodal-close" id="{{ recipe.id }}DeleteClose" data-remodal-action="close"></button>
                        <h4>Не показывать: {{ recipe.name_ru }}?</h4>
                        <form method="post" id="{{ recipe.id }}Delete">
                            {% csrf_token %}
                            <label for="id_delete_recipes" style="display: none;"></label><select style="display: none;" name="delete_recipes" id="id_delete_recipes" multiple="">
                            <option value="{{ recipe.id }}" selected=""></option>
                        </select>
                            <label for="id_delete_recipe" style="display: none;">Delete recipe:</label><select style="display: none;" name="delete_recipe" required="" id="id_delete_recipe" multiple="">
                            <option value="2" selected="">mad</option>
                        </select>
                            <br><br>
                            <button class="btn btn-sm btn-success mr-3" name="delete" type="submit">Нет</button>
                            <button class="btn btn-sm btn-outline-danger" data-remodal-action="cancel">Отменить</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>


{% block js2 %}
<script src="{% static '/assets/js/plugins.js' %}"></script>
<script src="{% static '/assets/lib/loaders.css/loaders.css.js' %}"></script>
<script src="{% static '/assets/js/theme.js' %}"></script>
<script src="{% static '/assets/lib/fancybox/jquery.fancybox.min.js' %}"></script>

<script src="{% static '/assets/lib/semantic-ui-accordion/accordion.min.js' %}"></script>
<script src="{% static '/assets/lib/semantic-ui-transition/transition.min.js' %}"></script>
<script src="{% static 'assets/lib/remodal/remodal.js' %}"></script>

<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

<script>
    {% for recipe in recipes %}
        $(document).ready(function() {
            $('#{{ recipe.id }}Add').ajaxForm(function() {
                document.getElementById("{{ recipe.id }}AddClose").click();
                alert("Блюдо успешно добавлено");
            });
        });
        $(document).ready(function() {
            $('#{{ recipe.id }}Delete').ajaxForm(function() {
                document.getElementById("{{ recipe.id }}DeleteClose").click();
                document.getElementById("ajax-text-me").click();
            });
        });
    {% endfor %}
    </script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ajax-text-me").click(function() {
            $.ajax({
                type: 'GET',
                async: true,
                url: '/ru/profile/{{ profile.slug }}/recipes/search/',
                data: "profile_slug={{profile.slug}}",
                success: function(data) {
                    $('.remodal-wrapper').remove();
                    $('.remodal-overlay').remove();
                    $("#search").replaceWith(data['html']);
                    $('html, body').animate({
                    scrollTop: $("#search").offset().top
                    }, 0);
                },
                dataType: 'json',
            });
        });
    });
</script>
{% endblock %}